---
title: 'Class08: In Class Work'
author: "Analine Aguayo"
date: "10/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## You can also download this file from the class website! 
mydata <- read.csv("https://tinyurl.com/expression-CSV",                    row.names=1)
head(mydata) 
nrow(mydata)
ncol(mydata)
```

```{r}
## lets do PCA 
pca <- prcomp(t(mydata), scale=TRUE)
pca
```
```{r}
pca <- prcomp(t(mydata), scale=TRUE)
attributes(pca)
```

```{r}
pca$x[,1]
plot(pca$x[,1],pca$x[,2])
```

```{r}
summary(pca)
```

```{r}
## Precent variance is often more informative to look at
pca.var <- pca$sdev^2 
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
pca.var.per
```

```{r}
pca.var <- pca$sdev^2 
pca.var.per <- round(pca.var/sum(pca.var)*100, 1) 
barplot(pca.var.per, main="Scree Plot",               
        xlab="Principal Component", ylab="Percent Variation")
```

```{r}
plot(pca)
```

```{r}
barplot(pca.var.per, main="Scree Plot", 
        xlab="Principal Component", ylab="Percent Variation")
```

```{r}
colvec <- as.factor( substr( colnames(mydata), 1, 2) )
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16, 
     xlab=paste0("PC1 (", pca.var.per[1], "%)"),
     ylab=paste0("PC2 (", pca.var.per[2], "%)"))
```
```{r}
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16, 
     xlab=paste0("PC1 (", pca.var.per[1], "%)"), 
     ylab=paste0("PC2 (", pca.var.per[2], "%)"))
identify(pca$x[,1], pca$x[,2], labels=colnames(mydata))
```

```{r}
substr(colnames(mydata),1,2)
```

